import { Typography } from "@mui/material";

export const Project = () => {
  return (
    <>
          <Typography variant="h3">Projects</Typography>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
          <div>私は阿部です私は阿部です</div>
    </>
  );
};
